collections:
  authors:
    output: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - github-pages
  
defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  
  - scope:
      path: ""
    values:
      layout: "default"